Fix crash when Hide App Icon is enabled alongside dynamic shortcuts
Fixes

```FATAL EXCEPTION: main
Process: com.github.metacubex.clash.meta, PID: 11066
java.lang.RuntimeException: Unable to create application com.github.kr328.clash.MainApplication
  at android.app.ActivityThread.handleBindApplication(ActivityThread.java:8144)
  at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2690)
  at android.os.Handler.dispatchMessage(Handler.java:132)
  at android.os.Looper.dispatchMessage(Looper.java:333)
  at android.os.Looper.loopOnce(Looper.java:263)
  at android.os.Looper.loop(Looper.java:367)
  at android.app.ActivityThread.main(ActivityThread.java:9287)
  at java.lang.reflect.Method.invoke(Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:566)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:929)
Caused by: java.lang.IllegalStateException: Launcher activity not found for package com.github.metacubex.clash.meta
  at android.os.Parcel.createExceptionOrNull(Parcel.java:3381)
  at android.os.Parcel.createException(Parcel.java:3357)
  at android.os.Parcel.readException(Parcel.java:3340)
  at android.os.Parcel.readException(Parcel.java:3282)
  at android.content.pm.IShortcutService$Stub$Proxy.setDynamicShortcuts(IShortcutService.java:599)
  at android.content.pm.ShortcutManager.setDynamicShortcuts(ShortcutManager.java:152)
  at androidx.core.content.pm.ShortcutManagerCompat.setDynamicShortcuts(ShortcutManagerCompat.java:473)
  at com.github.kr328.clash.MainApplication.setupShortcuts(MainApplication.kt:87)
  at com.github.kr328.clash.MainApplication.onCreate(MainApplication.kt:39)
  at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1396)
  at android.app.ActivityThread.handleBindApplication(ActivityThread.java:8139)
  ... 10 more
```